"""hadofix's suite: golden Dockerfiles in, expected diffs out, one case per rule.

Each directory under `tests/golden/` holds a Dockerfile, the hadolint JSON for
it (generated by the real linter — see that directory's README) and the two
halves of hadofix's output: the diff on stdout, the report on stderr.
Regenerate them with `make golden` after a deliberate change.
"""

import io
import os
import shutil
from pathlib import Path

import pytest

from hadofix import (
    APT,
    EX_FINDINGS,
    EX_NOINPUT,
    EX_OK,
    EX_UNAVAILABLE,
    Doc,
    Finding,
    fix_apt_lists,
    fix_base_pin,
    fix_pin_packages,
    main,
    own_findings,
    parse_findings,
    parse_ref,
    resolve_digest,
)

GOLDEN = Path(__file__).parent / "golden"
CASES = sorted(path for path in GOLDEN.iterdir() if path.is_dir())
UPDATE_GOLDEN = os.environ.get("HADOFIX_UPDATE_GOLDEN") == "1"


def run_case(
    case: Path,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    *argv: str,
) -> tuple[int, str, str]:
    """Run hadofix over a copy of `case`, with the temp path scrubbed back out."""
    shutil.copytree(case, tmp_path, dirs_exist_ok=True)
    code = main([str(tmp_path / "Dockerfile"), "--from-json", str(tmp_path / "hadolint.json"), *argv])
    captured = capsys.readouterr()
    return (
        code,
        captured.out.replace(f"{tmp_path}{os.sep}", ""),
        captured.err.replace(f"{tmp_path}{os.sep}", ""),
    )


@pytest.mark.parametrize("case", CASES, ids=lambda case: case.name)
def test_golden(case: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    code, diff, report = run_case(case, tmp_path, capsys)
    if UPDATE_GOLDEN:
        (case / "expected.diff").write_text(diff)
        (case / "expected.report").write_text(report)
    assert diff == (case / "expected.diff").read_text()
    assert report == (case / "expected.report").read_text()
    # Without --write nothing on disk changed, so a printed diff is still a
    # finding as far as a CI gate is concerned.
    unresolved = bool(diff) or "left for you" in report
    assert code == (EX_FINDINGS if unresolved else EX_OK)


@pytest.mark.parametrize("case", CASES, ids=lambda case: case.name)
def test_our_own_rules_are_idempotent(case: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Fixing a file twice changes it once.

    The second run is driven by an empty hadolint payload, which is what the
    linter answers for whatever hadofix already fixed; the HF rules recompute
    themselves from the rewritten file and have to stay quiet.
    """
    run_case(case, tmp_path, capsys, "--write")
    (tmp_path / "hadolint.json").write_text("[]")
    fixed = (tmp_path / "Dockerfile").read_text()
    main([str(tmp_path / "Dockerfile"), "--from-json", str(tmp_path / "hadolint.json"), "--write"])
    again, _report = capsys.readouterr()
    assert again == "", "the second run has nothing left to change"
    assert (tmp_path / "Dockerfile").read_text() == fixed


def test_write_applies_the_diff(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    case = GOLDEN / "dl3015-no-install-recommends"
    _code, diff, _report = run_case(case, tmp_path, capsys, "--write")
    assert "--no-install-recommends" in (tmp_path / "Dockerfile").read_text()
    assert diff, "the diff is still printed when it is applied"


def test_nothing_is_written_without_write(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    case = GOLDEN / "dl3015-no-install-recommends"
    run_case(case, tmp_path, capsys)
    assert (tmp_path / "Dockerfile").read_text() == (case / "Dockerfile").read_text()


def test_reads_hadolint_json_from_stdin(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text('FROM alpine:3.22\nUSER 10001\nCMD ["/app"]\n')
    payload = '[{"file":"Dockerfile","line":1,"column":1,"level":"info","code":"DL3059","message":"Multiple RUNs"}]'
    monkeypatch.setattr("sys.stdin", io.StringIO(payload))
    assert main([str(dockerfile), "--from-json", "-"]) == EX_FINDINGS
    assert "DL3059" in capsys.readouterr().err


def test_unknown_rules_are_listed_not_guessed_at(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text('FROM alpine:3.22\nUSER 10001\nCMD ["/app"]\n')
    payload = tmp_path / "hadolint.json"
    payload.write_text('[{"line":1,"level":"error","code":"DL3011","message":"Valid UNIX ports"}]')
    assert main([str(dockerfile), "--from-json", str(payload)]) == EX_FINDINGS
    out, err = capsys.readouterr()
    assert out == "", "a rule hadofix cannot fix produces no diff"
    assert "DL3011" in err


# --------------------------------------------------------------------------
# The parts that have to be right for every rule above.
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("ref", "expected"),
    [
        ("ubuntu", ("ubuntu", None, None)),
        ("ubuntu:24.04", ("ubuntu", "24.04", None)),
        ("registry.example.com:5000/app", ("registry.example.com:5000/app", None, None)),
        ("registry.example.com:5000/app:1.2", ("registry.example.com:5000/app", "1.2", None)),
        (f"alpine:3.22@sha256:{'a' * 64}", ("alpine", "3.22", f"sha256:{'a' * 64}")),
    ],
)
def test_parse_ref(ref: str, expected: tuple[str, str | None, str | None]) -> None:
    assert parse_ref(ref) == expected


def test_a_comment_inside_a_continuation_does_not_end_the_instruction() -> None:
    doc = Doc("FROM alpine:3.22\nRUN echo one \\\n# why we do this\n && echo two\n", Path("Dockerfile"))
    run = next(inst for inst in doc.instructions() if inst.keyword == "RUN")
    assert run.text == "RUN echo one && echo two"
    assert (run.start, run.end) == (1, 3)


def test_apt_cleanup_joins_a_multi_line_run() -> None:
    doc = Doc(
        "FROM debian:bookworm-slim\nRUN apt-get update \\\n && apt-get install -y curl\n",
        Path("Dockerfile"),
    )
    assert fix_apt_lists(doc, Finding("DL3009", 2, "info", "")).__class__.__name__ == "Fixed"
    assert doc.text.endswith(" && apt-get install -y curl \\\n && rm -rf /var/lib/apt/lists/*\n")


def test_pipefail_picks_the_shell_the_base_image_has(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text('FROM alpine:3.22\nRUN wget -qO- http://x | tar -xz\nUSER 10001\nCMD ["/app"]\n')
    payload = tmp_path / "hadolint.json"
    payload.write_text('[{"line":2,"level":"warning","code":"DL4006","message":"Set the SHELL option -o pipefail"}]')
    main([str(dockerfile), "--from-json", str(payload), "--write"])
    capsys.readouterr()
    assert '/bin/ash", "-o", "pipefail"' in dockerfile.read_text()


def test_a_version_is_taken_from_evidence_never_invented() -> None:
    doc = Doc("FROM debian:bookworm-slim\nRUN apt-get install -y curl\n", Path("Dockerfile"))
    refusal = fix_pin_packages(APT, doc, Finding("DL3008", 2, "warning", ""))
    assert "`curl`" in refusal.why
    assert doc.text.count("curl") == 1, "a refused fix leaves the file alone"


def test_a_stage_is_never_evidence_for_itself() -> None:
    """`FROM python:latest` is the finding, so it cannot also be the answer."""
    doc = Doc("FROM python:latest\n", Path("Dockerfile"))
    refusal = fix_base_pin(doc, Finding("DL3007", 1, "warning", ""))
    assert "--resolve-digests" in refusal.why
    assert doc.text == "FROM python:latest\n"


def test_the_base_pin_uses_the_resolver_only_when_the_file_has_no_answer() -> None:
    doc = Doc("FROM ubuntu\n", Path("Dockerfile"), resolver=lambda image, tag: f"sha256:{'0' * 64}")
    assert fix_base_pin(doc, Finding("DL3006", 1, "warning", "")).__class__.__name__ == "Fixed"
    assert doc.text == f"FROM ubuntu@sha256:{'0' * 64}\n"

    without = Doc("FROM ubuntu\n", Path("Dockerfile"))
    assert "--resolve-digests" in fix_base_pin(without, Finding("DL3006", 1, "warning", "")).why
    assert without.text == "FROM ubuntu\n"


def test_an_init_in_the_entrypoint_answers_hf1003() -> None:
    forking = Doc('FROM nginx:1.27\nUSER 10001\nCMD ["nginx", "-g", "daemon off;"]\n', Path("Dockerfile"))
    assert [f.code for f in own_findings(forking)] == ["HF1003"]

    with_init = Doc(
        'FROM nginx:1.27\nUSER 10001\nENTRYPOINT ["/sbin/tini", "--"]\nCMD ["nginx", "-g", "daemon off;"]\n',
        Path("Dockerfile"),
    )
    assert [f.code for f in own_findings(with_init)] == []


def test_an_entrypoint_script_that_execs_answers_hf1002(tmp_path: Path) -> None:
    (tmp_path / "entrypoint.sh").write_text('#!/bin/sh\nset -e\nexec "$@"\n')
    doc = Doc(
        'FROM alpine:3.22\nCOPY entrypoint.sh /entrypoint.sh\nUSER 10001\nENTRYPOINT ["/entrypoint.sh"]\n',
        tmp_path / "Dockerfile",
    )
    assert [f.code for f in own_findings(doc)] == []


def test_a_script_copied_with_the_build_context_is_still_found(tmp_path: Path) -> None:
    (tmp_path / "entrypoint.sh").write_text('#!/bin/sh\n/usr/local/bin/app "$@"\n')
    doc = Doc(
        'FROM alpine:3.22\nCOPY . /app\nUSER 10001\nENTRYPOINT ["/app/entrypoint.sh"]\n',
        tmp_path / "Dockerfile",
    )
    assert [f.code for f in own_findings(doc)] == ["HF1002"]


# --------------------------------------------------------------------------
# The CLI contract: a gate has to tell "not fixed" from "could not look".
# --------------------------------------------------------------------------


def test_missing_file_exits_ex_noinput(capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["/nonexistent/Dockerfile"]) == EX_NOINPUT
    assert "No such file" in capsys.readouterr().err


def test_a_missing_hadolint_is_not_a_finding(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text("FROM alpine:3.22\n")
    assert main([str(dockerfile), "--hadolint", "hadolint-that-is-not-installed"]) == EX_UNAVAILABLE
    assert "not found" in capsys.readouterr().err


def test_unreadable_json_exits_ex_unavailable(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text("FROM alpine:3.22\n")
    payload = tmp_path / "hadolint.json"
    payload.write_text("not json")
    assert main([str(dockerfile), "--from-json", str(payload)]) == EX_UNAVAILABLE
    assert "could not read the hadolint JSON" in capsys.readouterr().err


def test_parse_findings_ignores_what_it_does_not_understand() -> None:
    assert parse_findings("[]") == []
    assert parse_findings('[7, {"code": "DL3000", "line": "x"}]') == [Finding("DL3000", 1, "warning", "")]


# --------------------------------------------------------------------------
# --resolve-digests is the only part that touches the network.
# --------------------------------------------------------------------------


def test_resolve_digest_returns_none_for_a_qualified_registry() -> None:
    def unused_fetch(url: str, headers: dict[str, str] | None = None, digest_header: bool = False) -> str:
        raise AssertionError(f"a qualified registry must not be fetched: {url}")

    assert resolve_digest("ghcr.io/foo/bar", "latest", fetch=unused_fetch) is None


def test_resolve_digest_uses_the_injected_fetch() -> None:
    calls: list[str] = []

    def fake_fetch(url: str, headers: dict[str, str] | None = None, digest_header: bool = False) -> str:
        calls.append(url)
        if "auth.docker.io" in url:
            return '{"token": "t"}'
        assert headers is not None
        assert headers["Authorization"] == "Bearer t"
        assert digest_header
        return f"sha256:{'c' * 64}"

    assert resolve_digest("alpine", "3.22", fetch=fake_fetch) == f"sha256:{'c' * 64}"
    assert any("library/alpine" in url for url in calls)


# --------------------------------------------------------------------------
# With the real engine on PATH, end to end.
# --------------------------------------------------------------------------


@pytest.mark.skipif(shutil.which("hadolint") is None, reason="hadolint is not installed")
def test_hadolint_drives_one_pass_to_clean(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """One --write pass, and the linter that asked for the changes is quiet."""
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(
        "FROM debian:bookworm-slim\n"
        "RUN apt-get update && apt-get install -y curl=7.88.1-10+deb12u5\n"
        "CMD /usr/local/bin/app --port 8080\n"
    )
    assert main([str(dockerfile), "--write"]) == EX_OK
    capsys.readouterr()
    assert main([str(dockerfile)]) == EX_OK
    assert capsys.readouterr().out == "", "a second pass has nothing to say"
